service: aws-serverless-typescript

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment: 
    COGNITO_CLIENT_ID: 
      Ref: ${file(./src/config/cognito.yml):Resources.CognitoUserPoolClient}
    COGNITO_USER_POOL:
      Ref: ${file(./src/config/cognito.yml):Resources.CognitoUserPool}

functions:
  hello:
    handler: src/hello.handler
    events: 
      - httpApi: 
          method: GET
          path: /hello


plugins: 
  - serverless-offline

resources: ${file(./src/config/cognito.yml)}