service: aws-serverless-typescript

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: src/hello.handler
    events: 
      - httpApi: 
          method: GET
          path: /hello


plugins: 
  - serverless-offline

resources: ${file(./src/config/cognito.yml)}